---
- hosts: ppua
  become: true
  tasks:
    - name: Install apache
      apt: name=apache2 state=latest
    - name: Configure Apache
      copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
      with_items:
        - src: "./configs/apache2.conf"
          dest: "/etc/apache2/apache2.conf"
        - src: "./configs/000-default.conf"
          dest: "/etc/apache2/sites-available/000-default.conf"
    - name: Restart apache
      service:
        name: apache2
        state: restarted
    - name: Ensure apache is running and enabled
      service: name=apache2 state=started enabled=yes
